arraycontainer.go
Clarify a variable name and a comment.
=> Clarify orArray code/comments.

setutil.go, setutil_test.go
I think there was a problem with localintersection2by2. Added a failing test case to illustrate the problem, and a code change that passes the new test case and the existing test suite.
=> Fix bug in localintersection2by2

roaring.go, roaring_test.go
The code was computing the difference of containers but not using the result.
=> Fix AndNot behavior

roaring.go, roaringarray.go
With this change a cloned bitmap will initially share the containers with its parent bitmap. If there are changes to a container in the parent or clone we duplicate the container before modifying it. This PR implements this as part of the existing `Clone` method but we could create a new method to make this behavior opt-in (although I think in most cases the new behavior will be preferable).
This functionality adds an additional 24 bytes for the dirty slice and an additional byte per container to track the dirty state (if the `Clone` method is used).
There is a small 1-2% performance regression for `Add`.
I can't account for the changes to the sparse iterate and intersection benchmarks. Especially `BenchmarkSparseIterateBitset` which doesn't seem to use the roaring package at all. The …
=> Copy-on-write optimization for Clone()

fastaggregation.go, roaring.go
moving the if statement into the loop removes a level of indentation
=> cosmetic changes and simplify FastAnd

.gitignore, smat.go, smat_generate_test.go, smat_hits_test.go
One bug found from the fuzz testing runs so far was...
https://github.com/RoaringBitmap/roaring/issues/64
=> fuzz testing via the smat library

roaringarray.go
When using the updated RLE format (see #122) the main cost of constructing a large
bitmap with FromBuffer becomes growing the roaring array internal slices when
appending containers.
This commits fixes that. Now the `keys`, `containers` and `needCopyOnWrite` slices are
preallocated.
=> FromBuffer: allocate roaring array slices upfront

arraycontainer.go, rlei.go, rlei_test.go
This PR ports the [Java version of the array-run intersection algorithm](https://github.com/RoaringBitmap/RoaringBitmap/blob/43e3f466af230945eb8bc4abd60dc557a3e9e6d7/roaringbitmap/src/main/java/org/roaringbitmap/RunContainer.java#L300). In a private benchmark the performance improves significantly.
=> Port Java version of array-run container intersection algorithm

bitmapcontainer.go
Even though it adds code duplication the performance benchmarks make
this approach interesting:
```
benchmark                                            old ns/op     new ns/op     delta
BenchmarkRealDataFastOr/census-income_srt-8          617026        395117        -35.96%
BenchmarkRealDataFastOr/census1881_srt-8             1051061       935098        -11.03%
BenchmarkRealDataFastOr/weather_sept_85_srt-8        404418        297734        -26.38%
BenchmarkRealDataFastOr/wikileaks-noquotes_srt-8     214869        190827        -11.19%
```
Note that the benchmarks were done against FastOr in #143
=> Manually inline setBitmapRange to *bitmapContainer.lazyIOR function

benchmark_test.go
Some improvements to the running of benchmarks.
=> Benchmark fixes

roaring.go
=> *Bitmap.Or(*Bitmap): don't write to bitmaps with a CoW marker

serialization_test.go
Note this test fails with a slice out of bounds error.
Fixes #160
=> test known crashers from croaring

serialization_test.go
This catches and prints the panic and the stack trace.  We also avoid the false positive in the current test where an invalid input which doesn't panic "fails" the test (because it's checking for `err != nil`).
```
-- FAIL: TestSerializationCrashers (0.00s)
serialization_test.go:1002: crasher testdata/crashproneinput1.bin panicked: runtime error: slice bounds out of range
serialization_test.go:1003: stack:
goroutine 5 [running]:
runtime/debug.Stack(0xc4200d00f0, 0xc420058ba8, 0x4)
/Users/dgryski/go/src/go.googlesource.com/go/src/runtime/debug/stack.go:24 +0xa7
github.com/RoaringBitmap/roaring.TestSerializationCrashers.func1.1(0xc4200d00f0, 0xc420058ee0)
/Users/dgryski/go/src/github.com/RoaringBitmap/roaring/serialization_test.go:1003 +0x15f
panic(0x12a2240, 0x1465c90) …
```
=> nicer output for testing serialization crashers

roaringarray.go
=> Fix several panics from buffer-overruns in *Bitmap.FromBuffer

serialization_test.go
=> test crashers with ReadFrom

aggregation_test.go
=> TestParAggregations with different parallelism levels

arraycontainer.go, arraycontainer_test.go, bitmapcontainer.go, bitmapcontainer_test.go, roaring.go, roaring_test.go, roaringarray.go, runcontainer.go, runcontainer_test.go
i suppose i'm the first to need it?
=> Fixes #190, ports add offset from java

bitmapcontainer.go, bitmapcontainer_test.go, roaring_test.go
PrevSetBit was broken. Fix and add more tests.
=> Fix issue 213 - ReverseIterator is broken in some cases.

roaringarray.go
This is a purely cosmetic change. A static analysis tool
(built into IntelliJ IDEA) complained that `isRun` may not be initialized.
However that was impossible from the program flow it prompted me
to remove `haveRunContainers` and use a isRun nil check.
=> Instead of using `haveRunContainers` do a isRun nil check

serialization_littleendian.go, serialization_test.go
This is a new version of the stale PR https://github.com/RoaringBitmap/roaring/pull/226 which address @alldroll 's concerns.
I am hoping that @alldroll can review it.
=> Keep slice alive during unsafe operations

setutil.go, setutil_test.go
I try to solve #215, but the benchmarks show that there is a regression instead of performance enhancement. @lemire could you please take a look, perhaps I did something wrong.
=> Implement shotgun4Intersect

roaring.go, roaring_test.go, serialization_test.go, util.go
This fixes review notices from #222. The older branch has merge conflicts that why I have decided to create a new branch with implementations and tests.
=> Bitmap.AddOffset now accepts negative offset

BitSliceIndexing/bsi.go, BitSliceIndexing/bsi_test.go, roaring64/bsi64.go, roaring64/bsi64_test.go
Added new Min/Max BSI value feature.
=> Added MinMax() function.

serialization_frozen_test.go, serialization_littleendian.go
Added a convenience method to serialized in frozen format directly to an `io.Writer`.
Fixes #332
=> Implement frozen serialization to writer

roaring.go, roaring_test.go
Fixes https://github.com/RoaringBitmap/roaring/issues/336
=> Adding explicit panic for max and min

roaring.go, roaring_test.go
=> Implement range intersection

roaring.go
This addresses #94 
The change is simple (and simplistic, some improvements can be done down the line): instead of allocating a new container iterator whenever we change a key, we keep a slot for one of each kind in the outer iterator structure, and we update it and point to it when we switch keys. There's a small constant memory overhead due to this embedding, but overall it should be better for memory pressure than creating and discarding many tiny objects for most bitmaps.
=> Reduce allocations for iterators

README.md
I don't know what list I put it in, but I think it was the wrong one.
=> Actually show Husky in the README

roaring64/bsi64.go
A cleanup picked from my production branch at https://github.com/anacrolix/roaring/tree/anacrolix.
=> Tidy up BSI.GetValue

BitSliceIndexing/bsi.go
Remove creation of a slice that is subsequently not used
=> Remove unnecessary slice allocation

arraycontainer.go, arraycontainer_test.go, benchmark_test.go, runcontainer.go
Alternative to https://github.com/RoaringBitmap/roaring/pull/416
@neena  please review.
=> Faster faster iandnot

roaring.go, roaring64/bsi64_test.go, roaring64/roaring64_test.go, roaring64/roaringarray64.go, roaring_test.go, roaringarray.go, runcontainer.go, runcontainer_test.go, serialization_frozen_test.go
Fixes https://github.com/RoaringBitmap/roaring/issues/469
=> fixes Issue 469 (various Validate bugs)

roaring64/iter.go, roaring64/iter_test.go
This builds on the previous work in #475.
=> Clone Go 1.23 iterator support for roaring64.
