RoaringBitmap/roaring

roaring_test.go, roaringarray.go
The current method is doing a shallow copying of just the references to the elements in the roaring array.
This was causing panics during iteration because the parent bitmap could end up with an invalid structure (element with no values set).
=> Make Clone() a deep clone

arraycontainer.go, bitmapcontainer.go, roaring.go, roaring_test.go, roaringarray.go, util.go
Roughly follows the same implementation as the Java library.
The method on the containers can't be named `select` because it conflicts with the `select` keyword. I'm happy to change it to something better than `selectInt` but I couldn't come up with anything.
I noticed that the other methods on RoaringBitmap don't return an `error` value. I added one for `Select` since I didn't like the idea of having the method 'silently' fail by returning `-1` if it was given an input it couldn't handle.
I haven't done any benchmarking of `selectBitPosition` but I think it should be reasonably efficient.
=> Implement Select

fastaggregation.go, roaring.go, roaring_test.go, roaringarray.go
As described in #31 
For a [program](https://gist.github.com/bpot/49455d04f24da7e80582) which sets a single bit for each high-level key it reduces space usage by about 15% and object count by 40%.
Benchmarks appear unchanged.
```
HeapInUse 6072410112
HeapObjects 163851038
```
```
HeapInUse 5198454784
HeapObjects 98319536
```
=> Remove element type and use two parallel arrays for key/container

arraycontainer.go, benchmark_test.go, bitmapcontainer.go, roaringarray.go
Avoid using `binary.Write` which incurs non-trivial CPU and memory overhead. Improvements are more pronounced for bitmaps with more containers. This makes the serialization code a little less friendly but seems worth it.
```
benchmark                        old ns/op     new ns/op     delta
BenchmarkSerializationSparse     2198058       350539        -84.05%
BenchmarkSerializationMid        666467        163984        -75.40%
BenchmarkSerializationDense      71531         42038         -41.23%
benchmark                        old allocs     new allocs     delta
BenchmarkSerializationSparse     18319          1528           -91.66%
BenchmarkSerializationMid        1843           155            -91.59%
BenchmarkSerializationDense      43             5              -88.37%
benchmark …
```
=> Optimize serialization

roaring.go
Bitmap cardinality should be _less_ than old cardinality if an integer was removed
=> Fix CheckedRemove

roaring.go, serialization_test.go
Please consider the pull request for the methods  ToBase64 and FromBase64.  I have provided a test case.  I currently use the feature with a web service that stores the roaring bitmaps in a redis key value store.
=> methods to serialize and deserialize from base 64 encoded string

arraycontainer.go, bitmapcontainer.go, serialization_generic.go, serialization_littleendian.go
Serialized representations are just little endian byte slices, which can be obtained by referencing the data slice directly on certain platforms. 
On my machine, this results in 64%, 88%, and 90% reductions in runtime for `BenchmarkSerialization{Sparse,Mid,Dense}`:
$ git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
$ go test -bench BenchmarkSerialization -run -
PASS
BenchmarkSerializationSparse-8	    5000	    275510 ns/op
BenchmarkSerializationMid-8   	   10000	    128213 ns/op
BenchmarkSerializationDense-8 	  100000	     20826 ns/op
ok  	github.com/tgruben/roaring	5.112s
$ git checkout unsafe_serialization
Switched to branch 'unsafe_serialization'
$ go test -bench BenchmarkSerialization -run -
PASS
BenchmarkSerializationSparse-8	   20000 …
=> Use unsafe/reflect in serialization

roaring.go
Nearly a 20% speedup for GetCardinality().
```
benchmark                           old ns/op     new ns/op     delta
BenchmarkCountRoaring-4             76.2          62.8          -17.59%
BenchmarkUnionRoaring-4             463808        449793        -3.02%
BenchmarkIntersectionBitset-4       13821         13631         -1.37%
BenchmarkUnionBitset-4              7327540       7410987       +1.14%
BenchmarkSparseIterateRoaring-4     942088        951706        +1.02%
BenchmarkSetRoaring-4               72.7          72.0          -0.96%
BenchmarkSparseContains-4           115731        114669        -0.92%
BenchmarkGetTestBitSet-4            24.9          25.1          +0.80%
BenchmarkCountBitset-4              32299         32152         -0.46%
BenchmarkIntersectionRoaring-4      2238 …
```
=> roaring: iterate over containers directly

arraycontainer.go, benchmark_test.go, roaringarray.go
We do a lot of equality checks in our application to avoid `Xor` (and the associated allocations) if two bitmaps are equal.
Use slightly faster looping constructs for a ~20% speed up in the
normal case. Also, compare container identity to greatly speed up
comparison of cloned bitmaps.
```
benchmark                   old ns/op     new ns/op     delta
BenchmarkEqualsClone-4      148228        17037         -88.51%
BenchmarkEqualsSparse-4     166294        133839        -19.52%
```
=> Optimize equals

arraycontainer.go, benchmark_test.go, roaring.go
We almost always build bitmaps sequentially and I imagine that's not uncommon. This adds a special case to `(*arrayContainer).add()` which just does a simple append if the value is larger than all others in the container.
```
benchmark                           old ns/op     new ns/op     delta
BenchmarkSequentialAdd-4            38711199      16057751      -58.52%
```
Doesn't seem to hurt random add performance:
```
BenchmarkSetRoaring-4               71.4          70.5          -1.26%
```
=> Speed up sequential Adds (for sparse bitmaps)

benchmark_test.go, roaring.go
This still builds a new container if there is a container for a given key in both bitmaps. However it is much faster if the second bitmap is much sparser than the first and slightly faster for two random bitmaps with the same cardinality and range.
Fulfills part of #27.
```
benchmark                           old ns/op     new ns/op     delta
BenchmarkXorLopsided-4              441580        38068         -91.38%
BenchmarkXor-4                      1319948       1204654       -8.73%
benchmark                  old allocs     new allocs     delta
BenchmarkXorLopsided-4     3084           71             -97.70%
BenchmarkXor-4             3084           3059           -0.81%
benchmark                   old bytes     new bytes     delta
BenchmarkXorLopsided-4      313552        36512 …
```
=> Partial in place Xor

roaring.go
Should fix https://github.com/RoaringBitmap/roaring/issues/60
=> Fix typo in Bitmap.GetCopyOnWrite() parametering

roaring.go, roaring_test.go
Hi,
Here is a proposal of a `Stats()` method, similar to one in [gocroaring][goc-stats].
It gathers the same statistics, however unlike the _gocroaring_ version it returns a struct instead of a `map[string]uint64`. I think there are two advantages of this approach:
* discoverability of the gathered statistics when using an editor with auto-complete
* a mistyped statistic name in the client application will result in a compile time error instead of a runtime one
I'm hoping for comments on this PR. I'll add missing tests once the method interface is agreed on. :-)
[goc-stats]: https://github.com/RoaringBitmap/gocroaring/blob/master/gocroaring.go#L239
=> Bitmap.Stats() method proposal

roaringarray.go, serialization_test.go
Cast size to an uint16 so it overflows correctly in the case where there
are 0 containers.
Without this change trying to deserialize an empty bitmap returns an error: `error in readFrom: could not read the runContainer bit flags of length 8192 bytes: EOF`
I'm not sure if this is the best fix, it seems like an empty bitmap is a bit of a grey area -- based on reading the format spec it sounds like there should always at least be 1 container.
=> Fix deserialization of empty bitmaps

arraycontainer.go, arraycontainer_test.go, bitmapcontainer.go, example_roaring_test.go, rle.go, rle16.go, rle16_gen.go, rle16_gen_test.go, rle16_test.go, rle_gen.go, rle_gen_test.go, rle_test.go, rlecommon.go, rlei.go, rlei_test.go, roaring.go, roaringarray.go, serialization_test.go, util.go
Looking through the godoc (https://godoc.org/github.com/RoaringBitmap/roaring), I see that internal details like the RunIterator16 and RunIterator32 were left public, but should probably be private to not confuse those reading the docs. This PR makes them private, as runIterator32 and runIterator16.
In addition I added some detail to the godoc around the WriteToMsgpack/ReadFromMsgpack methods, and provided a pointer to the spec format for the WriteTo/ReadFrom docs.
=> private runIterators, msgpack docs++

.travis.yml
here's a small patch to the travis config to tell go to cross-compile for arm as well; this would have caught things like #89.
=> confirm build on arm via cross-compile

fastaggregation.go
This change converts containers in `lazyOR` methods to bitmap containers when computing an intersection.
It follows a similar pattern found in Java's RoaringBitmap [RoaringBitmap.naivelazyor](https://github.com/RoaringBitmap/RoaringBitmap/blob/master/roaringbitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java#L1628) method.
In our production case when using very wide unions this change improves performance significantly.
When evaluating an expression which consists of two wide unions (one of 161 bitmaps and another one of 144) the speed improvements was of a factor of x50.
Before:
```
and:497.120619ms, or:38.185436472s, andNot:12.385317ms
```
After:
```
and:30.566886ms, or:623.676526ms, andNot:10.220867ms
```
Sadly I cannot share the input bitmaps.
=> FastOr: force using bitmap containers

bitmapcontainer.go
Fixes a bug where BitmapContainer.lazyIOR(RunContainer) resulted in invalid cardinality of the returned container.
=> BitmapContainer invalidate cardinality on lazyIOR with RunContainer

parallel.go, parallel_benchmark_test.go, parallel_test.go
In this PR I parallelise roaring `And` and `Or` operations.
I depart from adding any shared aggregators, like in #104. The interface is kept simple – only two methods are added. `ParAnd` and `ParOr` take after `FastAnd` and `FastOr`. Resources (goroutines and channels) are not shared between invocations.
I use a heap as means of iterating through the passed bitmaps. Since t's slightly different from the one in `priorityqueue.go` it's implemented from scratch and not reused.
Tests are copied from `fast aggregation_test.go` and adapted.
I consider adding versions of `ParAnd` and `ParOr` in the future that would use shared resources (similar to ParAggregator from #104).
Fixes #38.
=> Parallel roaring bitmaps

parallel.go, parallel_test.go
This commit fixes an issue with `ParAnd` producing bitmaps that
contain empty containers, which AFAIK are invalid.
@lemire sorry for bothering you with a fixup to the recent PR. It's a case I haven't thought of before we had a discussion on intersections.
=> Fixes an issue with ParAnd producing bitmaps with empty containers

arraycontainer.go, bitmapcontainer.go, rle.go, rle16.go, roaringarray.go
This removes all unnecessary type conversions making the code somehow cleaner. OTOH I'm not sure if it'd be better to leave come of the type conversions in for code readability purposes.
Closes #114
=> Remove unnecessary type conversions

roaring.go, roaringarray.go, serialization.go, serialization_generic.go, serialization_littleendian.go, serialization_test.go
This PR introduces a method that allows to create a Bitmap from a byte buffer (`[]byte`) containing a serialized Roaring Bitmap with minimal memory copying.
Closes #116.
=> Bitmap.FromBuffer

fastaggregation.go, roaringarray.go
This PR fixes two issues with `FastOr` method. Both of them are related to `func (*Bitmap) lazyOR(*Bitmap) *Bitmap)`:
* in the case when containers where appended to the resulting bitmap copy-on-write marker was not carried over, which in some cases resulted in writing to a container that requires copy on write
* if a bitmap container was encountered in the receiver `Bitmap` copy-on-write marker was not respected
=> FastAggregation: ensure COW is respected

parallel.go
`bitmapContainerHeap` always returned writeable containers even though there was is need for that. This PR removes the unnecessary cloning of containers.
=> Parallel: remove redundant container copying

bitmapcontainer.go
Calling `newArrayContainerCapacity(bc.cardinality)` in unnecessary as `ac.loadData(bc)` re-creates the `ac.content`.
=> bitmapContainer.toArrayContainer: remove double slice allocation

serialization_generic.go
Fix `bitmapContainer.readFrom()` to compute cardinality just like
its _littleendian_ counterpart.
=> Generic bitmapContainer.readFrom() function should compute cardinality

arraycontainer_test.go, bitmapcontainer.go, rle16.go, rle16_gen.go, rle16_test.go, rlecommon.go, rlei.go, rlei_test.go, roaring_test.go, serialization.go, serialization_test.go
This pull request fixes #122.
As described in [the issue comment](https://github.com/RoaringBitmap/roaring/issues/122#issuecomment-348227024) I took the least invasive approach. It's mostly about:
* replacing existing referencing `interval16.last` with a respective function call
* using `newInterval16Range(start, last)` function to create `interval16`s
This made the task relatively easy. [Benchmark results](https://gist.github.com/maciej/dbff7ead05fed6f68243274bd593a1ed) don't show any significant performance impact.
As for message pack encoding and decoding – I've decided to patch the `_gen.go` files manually. As [we've discussed](https://github.com/RoaringBitmap/roaring/issues/116#issuecomment-339699383) removing it I think that should be sufficient.
Improved serialization routines will …
=> RLE16: align with Roaring Format Spec

arraycontainer_test.go, bitmapcontainer.go, rle16.go, rle16_gen.go, rle16_test.go, rlecommon.go, rlei.go, rlei_test.go, roaring_test.go, serialization.go, serialization_generic.go, serialization_littleendian.go, serialization_test.go
With introduction of a RLE memory layout matching RoaringFormatSpec
`byteSliceAsInterval16Slice` can be now be implemented using an
unsafe slice cast from `[]byte` to `[]interval16`
This pull request is based of #126.
=> Fast `byteSliceAsInterval16Slice`

parallel.go
This PR introduces two changes to parallel operations:
* it removes the unnecessary container pointer from `bitmapContainerKey` struct. This has a surprisingly significant impact on performance in the private benchmark[1] I'm using.
* it pools `[]container` slice passed to `orFunc` in `ParOr`. The measured perf. impact is not as significant as in the first change, but it's also positive
[1] I hope, hope to make some progress on #113 soon! :-)
=> Parallel operation changes

roaring_test.go, roaringcow_test.go
TestStats did not take into account CPU word length.
=> Fix TestStats for 32 bit architectures

roaringarray.go, serialization_generic.go
This PR introduces two changes to `roaringArray.fromBuffer` function:
* when creating the `isRun` bitmap instead looping over `unit64`s (and the remainder of bytes)  I "cast" the `isRun` bitmap to a `[]byte` slice using the `uint64SliceAsByteSlice` function and use the built-in `copy` fun to copy into the bitmap. I can observe a slight performance improvement on production systems due to that change
* a less significant change removes usage of `appendContainer` method and instead populates the `roaringArray` slices directly. I don't know if this has any impact on performance. Taking it on face value we eliminate the slice length change and the assignment. I have no measured if it has any impact on performance TBH, it'd likely be very insignificant if anything. Frankly, I simply prefer …
=> roaringArray.fromBuffer() changes

README.md, real_data_benchmark_test.go
This commit introduces benchmarks that use _real roaring datasets_[1].
I think it gets us covered pretty well in terms of benchmarking
`fast` and `par` aggregations.
Below are results from running on my Mac
(Late 2013 15' MBP with Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz):
```
⨯ env BENCH_REAL_DATA=1 go1.10rc1 test -bench 'BenchmarkRealData' -run -                                                14:31:58
goos: darwin
goarch: amd64
pkg: github.com/RoaringBitmap/roaring
BenchmarkRealDataParOr/census-income_srt-8         	    5000	    350298 ns/op
BenchmarkRealDataParOr/census-income-8             	    3000	    420514 ns/op
BenchmarkRealDataParOr/census1881_srt-8            	    2000	    687655 ns/op
BenchmarkRealDataParOr/census1881-8                	    2000	    680842 ns/op …
```
=> Benchmark ORs using _real roaring datasets_

fastaggregation.go
Fixes #138
Benchmark on the "real" dataset show a significant improvement:
```
benchmark                                            old ns/op     new ns/op     delta
BenchmarkRealDataFastOr/census-income_srt-4          841099        736937        -12.38%
BenchmarkRealDataFastOr/census-income-4              1248805       1157445       -7.32%
BenchmarkRealDataFastOr/census1881_srt-4             1992651       1295663       -34.98%
BenchmarkRealDataFastOr/census1881-4                 2797780       2096418       -25.07%
BenchmarkRealDataFastOr/dimension_003-4              50486750      2174251       -95.69%
BenchmarkRealDataFastOr/dimension_008-4              17056898      904640        -94.70%
BenchmarkRealDataFastOr/dimension_033-4              1246254       794440        -36.25% …
```
=> Eliminate unnecessary Bitmap allocation in (*Bitmap).lazyOR

aggregation_test.go, arraycontainer.go, benchmark_test.go, bitmapcontainer.go, manyiterator.go, real_data_benchmark_test.go, rle16.go, rle16_test.go, rlei.go, roaring.go, roaring_test.go, roaringarray.go
A higher performance bulk next method. +tests +benchmarks
From issue #123 
Sorry this has taken such a long time to put together.
Starting with the Bulk next functionality as hopefully it is less contentious.
In the end I went with a separate iterator as I was struggling to make the code compatible with a mixed `next`/`nextMany` mode (the existing iterator essentially prefetches the next value).
Also let me know areas you feel are missing tests/edge cases.
Anyway, the fun part! Benchmarks!
```
go test -bench BenchmarkNexts -benchmem -run -; and env BENCH_REAL_DATA=1 go test -bench BenchmarkRealDataNext -benchmem -run -
goos: darwin
goarch: amd64
pkg: git.soma.salesforce.com/WaveDataLib/vendor/github.com/RoaringBitmap/roaring
BenchmarkNexts/next__100.000000%-8         	     200	   9521314 …
```
=> Adds bitmap.NextMany() functionality 

roaring.go, roaringarray.go
Before this commit, Clear() would throw away any allocated slices, and
this change has Clear() instead resize slice lengths to 0, keeping the
underlying slice capacity.  Future operations that append() to the
slices might then see performance wins by avoiding some
memory allocations.
fromBuffer() is also enhanced to potentially reuse preallocated slice capacity.
An application that reuses a Bitmap instance via Clear() may see more performance gains than before.
=> Bitmap.Clear() retains preallocated slices for faster future ops

benchmark_test.go
Added two benchmarks -- one that allocates a brand new Bitmap on every
cycle, and another that reuses a single Bitmap instance on every cycle
via Clear().  I picked scenario numbers that attempt to produce more
underlying allocations in order to highlight the effect.
The numbers before the Clear() optimization...
```
BenchmarkBitmapReuseWithoutClear-8  500   2935449 ns/op   1103698 B/op   25049 allocs/op
BenchmarkBitmapReuseWithClear-8     500   2919375 ns/op   1103698 B/op   25049 allocs/op
```
From that, Clear() does not seem to have significant advantage over
just allocating a brand new Bitmap in time or memory used.
The numbers after the Clear() optimization that reuse slices...
```
BenchmarkBitmapReuseWithoutClear-8  500   2904732 ns/op   1103698 B/op   25049 allocs/op …
```
=> benchmark on Bitmap.Clear()

aggregation_test.go, arraycontainer.go, bitmapcontainer.go, parallel.go, real_data_benchmark_test.go, rle16.go, rlei.go, roaringarray.go, util.go
This commit introduces a faster _ParOr_. The algorithm is described informally in #140.
Benchmark data shows significant improvement compared to previous algorithm.
Benchmarks run on 15' 2017 MacBook Pro Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
```
benchmark                                           old ns/op     new ns/op     delta
BenchmarkRealDataParOr/census-income_srt-8          269673        194486        -27.88%
BenchmarkRealDataParOr/census-income-8              395797        310505        -21.55%
BenchmarkRealDataParOr/census1881_srt-8             723821        402359        -44.41%
BenchmarkRealDataParOr/census1881-8                 718247        573550        -20.15%
BenchmarkRealDataParOr/dimension_003-8              7466247       2197374       -70.57% …
```
=> Faster ParOr

.travis.yml, CONTRIBUTORS
also add my name to CONTRIBUTORS file as requested.
based on my experience the COVERALLS_TOKEN is needed, but based on goveralls readme : 
> For a public github repository, it is not necessary to define your repository key (COVERALLS_TOKEN).
so, try it without token first :) 
also if the goveralls fails, then try the normal `go test` like before. 
another thing, the repo token was publicly available in old `.travis.yaml` , it is advised to keep it a secret, so regenerating a new token is recommended.
=> push coverage report to travis (again)

bitmapcontainer_test.go, container_test.go, roaring.go, roaring_test.go, runcontainer_test.go, shortiterator.go
Update shortiterator.go hasNext and add tests for this and similar issues in the other container types.
The changes in roaring.go seemed reasonable after looking at the many Iterator code.
=> Fix for issue #191 - reverseIterator hasNext() termination condition is incorrect

roaring_test.go, util.go
TestPackageFlipMaxRangeEnd panics, and TestBitmapFlipMaxRangeEnd goes into an infinite loop. MaxRange is a desperately needed constant.
=> Add FlipMaxRangeEnd tests and MaxRange

arraycontainer.go, arraycontainer_test.go
I believe this clone is unnecessary for the in-place intersection. Showed up on our profiling!
=> remove unnecessary clone from arrayContainer.iand()

benchmark_test.go, roaringarray.go
This greatly reduces allocations when the writer has enough space to
hold the serialized bitmap.
```
name                   old time/op    new time/op    delta
SerializationSparse-8     127µs ± 6%      50µs ± 4%  -60.17%  (p=0.008 n=5+5)
SerializationMid-8       54.4µs ± 4%     8.2µs ± 4%  -84.98%  (p=0.008 n=5+5)
SerializationDense-8     6.43µs ± 4%    0.66µs ±13%  -89.78%  (p=0.008 n=5+5)
name                   old alloc/op   new alloc/op   delta
SerializationSparse-8     410kB ± 0%      12kB ± 0%  -96.97%  (p=0.008 n=5+5)
SerializationMid-8        277kB ± 0%       1kB ± 0%  -99.50%  (p=0.008 n=5+5)
SerializationDense-8     37.0kB ± 0%     0.1kB ± 0%  -99.61%  (p=0.008 n=5+5)
name                   old allocs/op  new allocs/op  delta
SerializationSparse-8      8.00 ± 0%      2.00 ± 0% …
```
=> Reduce buffering in WriteTo

bitmapcontainer.go, roaring_test.go, serialization_generic.go, serialization_littleendian.go, serialization_test.go
In some cases this could cause bitmaps to be serialized incorrectly.
Check if a bitmap needs to be converted to an array container after an
inplace-andNot operation.
This also adds a sanity check when writing bitmap containers to make
sure the cardinality is correct.
=> AndNot: avoid returning bitmapcontainer with arraycontainer cardinality

bitmapcontainer.go
This commit optimises iorBitmap by unrolling its main loop.
I noticed that this idea was also being tracked in #144, so I suppose this would close that out.
Benchmarks:
```
name                                     old time/op    new time/op    delta
RealDataFastOr/census-income_srt-8          354µs ± 7%     388µs ±11%   +9.60%  (p=0.000 n=10+10)
RealDataFastOr/census-income-8              774µs ± 5%     727µs ±12%   -6.10%  (p=0.007 n=10+10)
RealDataFastOr/census1881_srt-8             875µs ± 4%     870µs ± 1%     ~     (p=0.515 n=10+8)
RealDataFastOr/census1881-8                1.48ms ± 4%    1.22ms ± 2%  -17.97%  (p=0.000 n=10+9)
RealDataFastOr/dimension_003-8             1.23ms ± 5%    1.18ms ± 1%   -4.27%  (p=0.000 n=10+10)
RealDataFastOr/dimension_008-8              527µs ± 3% …
```
=> Improve performance of FastOR

benchmark_test.go, roaring.go
- Makes `MarshalBinary` an alias to `ToBytes`
- Removes unnecessary intermediate `bufio.Reader` from `UnmarshalBinary`
```
name               old time/op    new time/op    delta
MarshalBinary-4       125µs ± 3%      69µs ± 0%  -44.26%  (p=0.008 n=5+5)
UnmarshalBinary-4     100µs ± 0%      58µs ± 3%  -41.85%  (p=0.016 n=4+5)
name               old alloc/op   new alloc/op   delta
MarshalBinary-4       509kB ± 0%     276kB ± 0%  -45.73%  (p=0.079 n=4+5)
UnmarshalBinary-4     291kB ± 0%     155kB ± 0%  -46.60%  (p=0.008 n=5+5)
name               old allocs/op  new allocs/op  delta
MarshalBinary-4        10.0 ± 0%       9.0 ± 0%  -10.00%  (p=0.008 n=5+5)
UnmarshalBinary-4       340 ± 0%       337 ± 0%   -0.88%  (p=0.008 n=5+5)
```
=> Improve MarshalBinary and UnmarshalBinary performance

roaring.go, roaringarray.go, roaringcow_test.go, serialization_test.go
This adds FlushCopyOnWrite() to address https://github.com/RoaringBitmap/roaring/issues/219. Interested in hearing what testing we should be doing. Also, I think it is right not to touch the roaring array's CopyOnWrite field. Is that correct?
@lemire @maciej
=> add flushCopyOnWrite() call so that source bitmaps can be unmapped.

arraycontainer.go, arraycontainer_test.go, benchmark_test.go, bitmapcontainer.go, bitmapcontainer_test.go, container_test.go, roaring.go, roaring_test.go, roaringarray.go, runcontainer.go, runcontainer_test.go, shortiterator.go
Implements the ability to skip values by using `IntPeekable` interface. Was inspired by https://github.com/RoaringBitmap/RoaringBitmap implementation. 
This should be very useful for `threshold intersection` algorithms such as `CPMerge` and `MergeSkip` described in `Efficient Merging and Filtering Algorithms for Approximate String Searches` and `Simple and Efficient Algorithm for Approximate Dictionary Matching`. Go implementations can be founded here https://github.com/alldroll/suggest/tree/master/pkg/merger
=> Peekable iterator

container_test.go, roaring_test.go, runcontainer.go
I have found a really tricky bug. When we are trying to advance a `runIterator16` on an item, that is located in the first `interval16` after the `start` item, we are getting an error "index out of range".  This pull request fixes this bug and checks it through tests
=> Fixed bug with runtime container "index out of range".

setutil.go, setutil_test.go
with set2 being empty the difference function would panic on trying to fill buffer whose length is 0.
=> Fix difference panic on empty set2

roaringarray.go
This might be faster than another PR:
https://github.com/RoaringBitmap/roaring/pull/246
=> No longer allocate temporary memory when serializing

arraycontainer.go, benchmark_test.go, bitmapcontainer.go, roaring.go, roaring_test.go, roaringarray.go, runcontainer.go
One of our applications currently makes heavy use of Iterators.  We noticed that they are a minor but noticeable source of allocations (along with the associated cpu & gc cost) in our application due to each Iterator being heap allocated along with the internal iterators each container creates.
This commit provides an alternate Iterate() method with a callback that iterates the bitmap in place, invoking the callback for each value.  This avoids allocations entirely at the cost of some code duplication
Below are benchmarks, you can see that `iterate` doesn't allocate and is slightly faster.
```
$ go test -run=none -bench=BenchmarkIterateRoaring -count 25
$ benchstat
name                                  time/op
IterateRoaring/iterator-compressed-8  519µs ± 3%
IterateRoaring/iterator-8 …
```
=> Add Iterate() method for iterating the bitmap without an iterator

arraycontainer.go, arraycontainer_test.go, benchmark_test.go, bitmapcontainer.go, bitmapcontainer_test.go, fastaggregation.go, fastaggregation_test.go, roaringarray.go
This method provides shortcut for `rb.And(FastOr(bitmaps...))`.
I tried mainly to minimize allocations, as huge amounts of garbage are a major concern in my current workflow.
Benchmark results:
```
$ go test -v -bench AndAny -benchmem -run=^$
goos: linux
goarch: amd64
pkg: github.com/RoaringBitmap/roaring
BenchmarkAndAny
BenchmarkAndAny/small-base_or-first
BenchmarkAndAny/small-base_or-first-4                 24          46254232 ns/op        35107140 B/op       9197 allocs/op
BenchmarkAndAny/small-base_and-first
BenchmarkAndAny/small-base_and-first-4              7383            148264 ns/op           26448 B/op       1485 allocs/op
BenchmarkAndAny/small-base_AndAny
BenchmarkAndAny/small-base_AndAny-4                  318           3369823 ns/op           46909 B/op         10 allocs/op …
```
=> add AndAny method

bitmapcontainer.go, manyiterator.go, roaring.go, roaring64/aggregation64_test.go, roaring64/fastaggregation64.go, roaring64/fastaggregation64_test.go, roaring64/iterables64.go, roaring64/iterables64_test.go, roaring64/parallel64.go, roaring64/roaring64.go, roaring64/roaring64_test.go, roaring64/roaring64cow_test.go, roaring64/roaringarray64.go, roaring64/util.go, runcontainer.go, util.go
Fixes #136
This PR is very much a work-in-progress. I've tried to stay with the original 32 bit method signatures as much as possible. Serialization is explicitly not part of this PR.
=> Add 64 bit implementation of roaring.Bitmap

BitSliceIndexing/bsi.go
This should be much faster in general and give the same result.
=> use AndCardinality for calculating BSI sum rather than iterator.

roaring64/roaring64.go
This is a bug fix for #270 , PTAL.
=> roaring64.go: fix uint64 print.

benchmark_test.go, roaring.go, roaringarray.go, roaringcow_test.go
This is a change for #265, with a benchmark that demonstrates the effect that it has. The actual change is good to go, although I'm not certain if it is in the most elegant manner.
The benchmark is kinda hideous, but gets at the target of this change: If the receiving bitmap's containers are COW, as they tend to be if deserialized from bytes, then you end up doing allocations both within `getWritableContainerAtIndex()` and `ior()`, as your array containers need to be extended again when ior() is called. The benchmark results below show this, and in general performance is the same or better, although there are circumstances where it does degrade slightly. 
The benchmark is targeted at producing bitmaps entirely of array containers, albeit of varying numbers of containers and densitities. …
=> Minimize clones (WIP)

arraycontainer.go, roaring_test.go
This contains a pair of changes to arrayContainer that together greatly reduce allocations in `arraycontainer.iorArray()`.
The problem(s):
Currently it is possible for an array container to allocate a new slice with every call to iorArray(), even if no elements are actually added to it. The clearest cause is repeatedly having `maxPossibleCardinality > arrayDefaultMaxSize`. The current code can repeatedly allocate a new 8192 byte slice for a bitmap container, even if it always gets garbage collected. This is most clearly demonstrated in RepeatedSelfArrayUnion, and was the issue that I opened #258 to address.
However, even with this, arrayContainer can still allocate a very large number of slices. In particular, every time a larger value of maxPossibleCardinality is reached, a new slice has …
=> Array container alloc optimizations

arraycontainer.go
Though 8192 is hard constant, we don't want numerical constants all over the code.
=> Minor tweak.

serialization_generic.go, serialization_littleendian.go
Fixes https://github.com/RoaringBitmap/roaring/issues/284
=> More generous detection of little endian systems

bitmapcontainer.go, bitmapcontainer_test.go, roaring_test.go
Shifting bits and using binary operations instead of multiplication, division and modulo yielded the following results.
```
name                                                                  old time/op    new time/op    delta
ShortIteratorAdvanceArray/init_size_1_shortIterator_advance-12          41.8ns ± 0%    40.3ns ± 0%   -3.48%  (p=0.016 n=4+5)
ShortIteratorAdvanceArray/init_size_650_shortIterator_advance-12        77.2ns ± 1%    76.1ns ± 2%     ~     (p=0.659 n=5+5)
ShortIteratorAdvanceArray/init_size_6500_shortIterator_advance-12       86.8ns ± 2%    89.4ns ± 5%     ~     (p=0.056 n=5+5)
ShortIteratorAdvanceArray/init_size_65535_shortIterator_advance-12      90.2ns ± 0%    90.0ns ± 2%     ~     (p=0.651 n=5+5)
ShortIteratorNextArray/init_size_1_shortIterator_next-12 …
```
=> optimise bitmaps

parallel.go
Sadly I do not have a corresponding unit test. However the overflow is quite credible and this change should avoid it.
Fixes https://github.com/RoaringBitmap/roaring/issues/303
=> Minimal fix for 303.

runcontainer_test.go
I'm improving run containers and kept getting caught on this test until I realized this check was incomplete.
=> treat lazyIOR as in-place in run container test.

fastaggregation.go
As discussed in #309, not using the returned value of `ior()` makes the correctness of AndAny conditional on implementation details.
=> Stop assuming ior is in-place for AndAny.

arraycontainer.go, runcontainer.go
Based on profiling of our systems, run containers are a big bottleneck for our system, in particular because of the memory and CPU performance of several union methods. 
This change introduces a new private method `runArrayUnionToRuns()` which does a zipper union between an array container and a run container to construct a fresh slice of intervals.
The results on our workload are great, with a 40% reduction in CPU usage, 35% reduction of wallclock time, and a 60% reduction in bytes allocated. There isn't currently any reuse of slices for the in-place calculations, which there could be, so overall allocations are not reduced.
=> faster run container unions.

bitmapcontainer.go, bitmapcontainer_test.go
While porting the shift feature to CRoaring I found `bitmapContainer.addOffset` to be broken. Instead of `OR`ing the bits from two successive words it would pick either the high or the low word depending on if the low one was empty.
=> OR the intermediate values in bitmapContainer.addOffset

parallel.go
ParOr was returning a reference to the input when only one bitmaps was passed. This introduces aliasing and is inconsistent with the other union functions. Return a copy instead.
=> Fix aliasing in ParOr

roaring64/parallel64.go, roaring64/roaring64_test.go, roaring64/roaring64cow_test.go, roaring64/util.go
In some instances, the ParOr function in roaring64 could encounter an integer overflow which may lead to a size zero channel. A channel with size zero might block indefinitely under some systems. This would not show up as a data race.
=> Fixing a deadlock.

BitSliceIndexing/bsi.go, BitSliceIndexing/bsi_test.go, roaring64/bsi64.go, roaring64/bsi64_test.go, roaring64/parallel64.go, roaring64/roaring64_test.go, roaring64/roaring64cow_test.go, roaring64/util.go
Fix for issue #315.  BSI were not correctly supporting twos complement negative values.
=> Fix issue #315, Negative BSI values fail range comparisons.

benchmark_memory_test.go, benchmark_test.go
This should help `benchstat` and `benchcmp` to avoid getting confused by spurious prints in the output.
=> Report heap use as metrics in benchmark

roaringarray.go
The spec at https://github.com/RoaringBitmap/RoaringFormatSpec says:
> The 16 least significant bits of the 32-bit cookie have value SERIAL_COOKIE. In that case, the 16 most significant
> bits of the 32-bit cookie are used to store the number of containers minus 1. That is, if you shift right by 16 the
> cookie and add 1, you get the number of containers.
However, the uint16() cast prior to + 1 causes a uint16 overflow, which results in a size of 0, which is invalid.
=> fix deserialization when size=0xFFFF

go.mod, go.sum
When I implemented the frozen format the initial tests depended on real datasets and gocroaring. The dependencies in go.mod and go.sum lingered after the revert.
=> Remove forgotten unneeded deps

arraycontainer.go, arraycontainer_test.go, bitmapcontainer.go, bitmapcontainer_test.go, roaring.go, roaringarray.go, runcontainer.go, runcontainer_test.go
This work reduces allocation made by the `addOffset` methods applied to containers by `AddOffset64`.
First, it replaces the return of a slice with the low and high parts by a simple multivalue return.
Presumably this was simply taken from the Java implementation, where multivalue returns aren't present.
This saves two allocations (one for the header, one for the buffer) per container and adds some brevity.
Then, it replaces the use of empty containers in the output by a `nil`-is-empty protocol.
Implementations detect whether they'll be returning 0, 1 or 2 containers eagerly and avoid unneeded allocation.
The 0 case could be omitted.
Special care was taken to avoid the creation of boxed nil pointers.
=> Addoffset allocation optimizations

roaring.go
This PR skips computation of shifted containers that would be discarded due to  out of bounds keys in the case of container unaligned offsets.
It should both reduce load on the GC due to these temporary objects and CPU use due to the computation itself.
=> More AddOffset optimizations

roaring.go
`GetCardinality` effectively iterates the whole set of containers and
gets the cardinality of each, so computing it first to check whether
there can be an i-th element without making the iteration effectively
makes it iterate through the whole thing twice.
=> Remove cardinality computation from Select

benchmark_test.go, roaring.go, roaring_test.go, serialization_generic.go
This is a proof of concept for hashing roaring bitmaps.  
It works by writing to a customizable `hash.Hash`, for each key, a sequence composed of the given key as an LE 16 bit number followed by the values represented by its matching container in the same format, followed by a `0x0000` delimiter.  
Since no empty containers are kept in the bitmap there's no conflict with a container starting with the `0` value, because a separator following a key is simply impossible.  
Because we store the key and the the values following it is impossible for two containers corresponding to different sets but with the same lower parts to end up passing the same input for the hasher, so any collisions that could happen are caused by the hashing algorithm itself, rather than by two different sets creating …
=> Implement hashing (#198)

roaring.go
Comparing equality between high bits directly rather than shifting each
time, provides a slight boost to some operations.
benchstat output:
ShortIteratorAdvanceArray/init_size_1_shortIterator_advance-8
56.5ns ±17%    50.9ns ±18%  -9.91%  (p=0.050 n=29+5)
ShortIteratorAdvanceArray/init_size_650_shortIterator_advance-8
88.2ns ±12%    84.8ns ±14%    ~     (p=0.706 n=28+5)
ShortIteratorAdvanceArray/init_size_6500_shortIterator_advance-8
99.0ns ±10%    93.1ns ±10%    ~     (p=0.183 n=28+5)
ShortIteratorAdvanceArray/init_size_65535_shortIterator_advance-8
104ns ± 6%      98ns ±13%    ~     (p=0.099 n=25+5)
SparseAdvanceRoaring/advance_from_1-8
84.9ns ± 7%    83.3ns ±19%    ~     (p=0.827 n=28+5)
SparseAdvanceRoaring/advance_from_2-8
88.8ns ±24%    86.9ns ±15%    ~     (p=0.741 n=29+5) …
=> Microoptimization for AdvanceIfNeeded

README.md
Update downstream torrent user to anacrolix/torrent. CloudTorrent uses anacrolix/torrent under the hood, it doesn't use it directly itself. All downstream users of anacrolix/torrent use roaring transitively.
=> Update torrent downstream user

runcontainer.go, runcontainer_test.go
runArrayUnionToRuns had a bug where it was returning the cardinality, rather than one less than the cardinality. This caused #358, in particular the value returned at https://github.com/RoaringBitmap/roaring/blob/294097852484945d6bc34af513641f3ec5cb9767/runcontainer.go#L2157. This only led to incorrect _behavior_ when the union result was a full container. This caused the cardMinusOne to overflow to 0, so it'd get incorrectly converted to an array container. Unfortunately, the runcontainer's toArrayContainer() method has never been safe to call if the size is larger than `arrayDefaultMaxSize`, as it doesn't handle `iaddRange()` returning a new container.
I wrote a unit test for this case, which now passes.
=> bugfix: return correct cardMinusOne in runArrayUnionToRuns

go.mod, go.sum
Bump github.com/stretchr/testify to v1.7.0 to update gopkg.in/yaml.v2 version contains XML Entity Expansion vulnerability
Signed-off-by: Alex Goncharov <github@b4bay.com>
https://github.com/docker/cli/pull/2117
https://gitlab.com/gitlab-org/security-products/gemnasium-db/-/blob/master/go/gopkg.in/yaml.v2/GMS-2019-2.yml
=> Bump github.com/stretchr/testify to v1.7.0

BitSliceIndexing/bsi_test.go, README.md, roaring64/bsi64_test.go, roaring64/roaring64_test.go, roaring64/serialization_test.go, serialization_frozen_test.go, serialization_test.go
Some people want to run our tests without file access. We will allow it, but it is a troubling idea because we effectively allow partial testing. We will be issuing warnings.
=> Allowing soft disabling of IO tests.

BitSliceIndexing/bsi.go, roaring64/bsi64.go
Somehow this got missed when BSI was added. There are no existing tests that check this directly, but it's easily discoverable.
=> Modify BSI existence bitmap on Increment

roaring64/bsi64-fuzz_test.go, roaring64/bsi64.go, roaring64/bsi64_test.go
This is an update to https://github.com/RoaringBitmap/roaring/pull/381.
I added fuzzing for the BSI storage, enabled for go1.18.
I removed all the unnecessary bitmap framing: roaring.Bitmaps are self contained and you can serialize them consecutively without any extra framing required. This significantly reduces overhead and storage requirements.
I removed a lot of excessive allocation, particularly around the framing above.
I added BSI.Equal, which was helpful in the tests.
I fixed the compatibility issue with go1.14.
=> Add BSI WriteTo, ReadFrom and Equal

roaring64/roaring64cow_test.go, roaring64/roaringarray64.go, roaringcow_test.go
It seems that the issue that is we fail to clone the 32-bit bitmaps within the 64-bit structure.
Verifies issue 386
If merged... this 
Fixes https://github.com/RoaringBitmap/roaring/issues/386
=> Verifying issue 386

roaring64/bsi64.go
A missing method implemented in my production branch at https://github.com/anacrolix/roaring/tree/anacrolix.
=> Add BSI.GetSizeInBytes

internal/byte_input.go, roaring.go, roaring64/roaring64.go, roaring64/roaringarray64.go, roaring64/serialization_test.go
We are utilizing [the rocksdb merge operator](https://github.com/facebook/rocksdb/wiki/Merge-Operator) to manipulate values that are encoded by roaring bitmap. The bitmap will be read from disk and merged together, these frequent operations can consume significant CPU resources due to the memory allocations.
So, I am proposing to add an alternative function called FromUnsafeBytes to address this problem. The caller can decide whether to make a copy or reuse those byte buffers if necessary.
The benchmark results (note that I have allocated a large buffer and made a copy before FromUnsafeBytes)
```
$ gotest -v -benchmem -bench=.+ -run=Benchmark -benchtime=100000x -count=1
goos: darwin
goarch: arm64
pkg: github.com/RoaringBitmap/roaring/roaring64
BenchmarkUnserializeFromUnsafeBytes …
```
=> Add FromUnsafeBytes to prevent small allocations caused by ByteInputAdapter

roaring64/bsi64.go, roaring64/roaring64.go
A performance improvement I made after Bitmap allocation became the most significant performance issue after fixing https://github.com/RoaringBitmap/roaring/pull/383. This avoids allocating bitmaps all over the heap and packs them together in the BSI for a good performance boost.
There's a small change to when RunOptimize is called, I found the existing behaviour was incorrect after extensive testing. This is probably related to my observation in https://github.com/RoaringBitmap/roaring/pull/383#issuecomment-1455553028.
This fix is picked from my production branch at https://github.com/anacrolix/roaring/tree/anacrolix.
=> Remove unnecessary allocations in 64 bit BSI

benchmark_test.go, bitmapcontainer.go, internal/byte_input.go, roaring.go, roaring_test.go, roaringarray.go, runcontainer.go, serialization.go, serialization_frozen_test.go, serialization_littleendian.go, serialization_test.go
In Go, garbage collection is a substantial cost and burden. For this reason, we put a lot of effort in efficient bitmap deserialization, optimizing the case where the resulting bitmaps are effectively immutable most of the time.
It appears that, over time, we made it so that all bitmap deserialization routines would have containers with copy-on-write set to true. Indeed, `roaringArray` has `ra.needCopyOnWrite[i] = true` in its `readFrom` function. In turn, this `readFrom` method is called from multiple functions such as `UnmarshalBinary`  or `FromBase64`.
What the `ra.needCopyOnWrite[i] = true` line does is that it ensures that we never try to write to the slices/buffers. Instead, if a modification is needed, we just make a whole copy. This is important because the byte array we use in a …
=> Verifying and fixing issue 396 :  `UnmarshalBinary`  or `FromBase64` should not have their containers marked as needing copy-on-write

BitSliceIndexing/bsi.go, BitSliceIndexing/bsi_test.go
Removed the use of goroutines in SetValue. 
My guess is that these made sense when bitmap adding was less efficient. Now they add unnecessary overhead.
Also added a check to make sure bits in their respective bitmaps are only unset for those where columnID is in the existence bitmap.
With goroutines:
```
goos: windows
goarch: amd64
pkg: github.com/RoaringBitmap/roaring/BitSliceIndexing
cpu: 12th Gen Intel(R) Core(TM) i5-12600K
BenchmarkSetRoaring
BenchmarkSetRoaring-16            157240              8431 ns/op
PASS
```
Without goroutines:
```
goos: windows
goarch: amd64
pkg: github.com/RoaringBitmap/roaring/BitSliceIndexing
cpu: 12th Gen Intel(R) Core(TM) i5-12600K
BenchmarkSetRoaring
BenchmarkSetRoaring-16           2262295               498.2 ns/op
PASS
```
=> Don't use goroutines in SetValue

roaring.go, roaring_test.go
This commit introduces ToDense and FromDense as methods in Bitmap. They make conversion to and from dense bitmaps like https://github.com/bits-and-blooms/bitset or https://github.com/kelindar/bitmap performant and simple.
```
name                                     time/op
FromDense/bitmap-4097-10                   1.62µs ± 0%
FromDense/run-4098-10                      1.25µs ± 0%
FromDense/array-4096-10                    1.60µs ± 0%
FromDense/bitmaps-and-runs-300000-10       3.76µs ± 0%
WriteDenseTo/bitmap-4097-10                17.1ns ± 0%
WriteDenseTo/run-4098-10                   31.2ns ± 0%
WriteDenseTo/array-4096-10                 8.69µs ± 0%
WriteDenseTo/bitmaps-and-runs-300000-10    1.53µs ± 0%
name                                     speed
FromDense/bitmap-4097-10 …
```
=> roaring: implement ToDense and FromDense

roaring64/roaring64.go, roaring64/roaring64_test.go, roaring64/serialization_test.go
When deserializing a 64-bit roaring bitmap, the code would first try to deserialize a 32-bit bitmap. It would usually work, but sometimes it would fail (see https://github.com/RoaringBitmap/roaring/issues/409) because the number of containers would be recognized as a cookie.
This PR disables this attempt at supporting 32-bit bitmaps loading from 64-bit bitmaps.
To compensate the reduction in functionality, the PR adds `Roaring32AsRoaring64`: users that have 32-bit bitmaps that they want to load as 64-bit bitmaps can just load them as 32-bit bitmaps and them call `Roaring32AsRoaring64` to wrap them so that they appear as 64-bit bitmaps.
I do not include a test for issue 409 because it requires a non-trivial amount of memory to trigger it and I am concerned about stress on our CI.
=> Fixing issue 409

roaring64/roaring64.go
Before this change, `roaring64.Bitmap.ReadFrom` didn't properly handle `io.Reader` implementations that read less than `len(p)` bytes on a call to `Read`.
Fixes #411.
Tested successfully via `go test -v ./..`.
=> Use io.ReadFull in roaring64.Bitmap.ReadFrom

README.md
FrostDB uses roaring Bitmaps in the query layer.
=> Add FrostDB to README

arraycontainer.go, arraycontainer_test.go, benchmark_test.go, runcontainer.go
Improve the performance of in-place AndNot between array and run containers. The current approach converts both to bitmaps, performs the AndNot, and then returns the result. 
Instead, this approach scans the list of runs in the run container, and calls `iremoveRange` on each one in the array container. 
Before:
```
BenchmarkAndNot/inPlace=true/left=array/right=run-10        	  121395	     11533 ns/op
```
After:
```
BenchmarkAndNot/inPlace=true/left=array/right=run-10       	 1308555	      2369 ns/op
```
=> improve performance of AndNot between array and run containers

benchmark_test.go, bitmapcontainer.go, bitmapcontainer_test.go
Rather than converting a run container to a bitmap container and then performing iandnot, call removeRange directly. 
```
name                                          old time/op  new time/op  delta
AndNot/inPlace=true/left=bitmap/right=run-10  6.71µs ±32%  3.08µs ±45%  -54.05%  (p=0.000 n=20+17)
```
=> faster iandnot between bitmap containers and run containers

benchmark_test.go, bitmapcontainer.go
Faster and fewer allocs! 
```
name                                            old time/op    new time/op    delta
AndNot/inPlace=true/left=bitmap/right=array-10    12.9µs ±72%     7.3µs ±26%   -43.44%  (p=0.000 n=10+10)
name                                            old alloc/op   new alloc/op   delta
AndNot/inPlace=true/left=bitmap/right=array-10    8.22kB ± 0%    0.00kB       -100.00%  (p=0.000 n=10+10)
name                                            old allocs/op  new allocs/op  delta
AndNot/inPlace=true/left=bitmap/right=array-10      2.00 ± 0%      0.00       -100.00%  (p=0.000 n=10+10)
```
=> faster iandnot between bitmap and array containers

arraycontainer.go, arraycontainer_test.go, bitmapcontainer.go, bitmapcontainer_test.go, roaring.go, roaring_test.go, roaringarray.go, runcontainer.go, runcontainer_test.go, serialization_frozen_test.go, serialization_littleendian.go
@lemire 
1. Starts work for https://github.com/RoaringBitmap/roaring/issues/400
2. I read the original paper on Roaring as well as the one adding run containers, so I think I understand the very basics of the invariants to be checked. I'm sure there are other approaches.
3. If the overall approach looks good, I'm planning on looking at more ways to corrupt the containers via code eg changing container sizes, breaking sort orders.
4. I looked at the serialization methods, and have a rough understanding of how that works. Do you think it's worthwhile to try to corrupt a serialized byte stream and see if it's detected when de-serialized. I think that would be moderately difficult for me to do but might be a good test.
=> Start validation

README.md, example_roaring_test.go
Now that we have `Validate()`, we need to tell the world about it.
=> documenting validation

bitmapcontainer.go, bitmapcontainer_test.go, manyiterator_test.go, setutil.go, setutil_test.go
Generally improving code coverage. If there are specific areas that could benefit the most please let me know. Otherwise I'm just going off the code coverage report and areas I'm familiar with.
=> Code Coverage: Set Util

roaring64/roaring64.go, roaring64/roaring64_test.go, roaring64/roaringarray64.go, roaring64/serialization_test.go
Starts validation for roaring64.
I hadn't looked much at the 64 bit stuff before. It looks like the data structure just nests the keyspace with 32 bit key -> 32 bit key -> 16 bit value. I'll think on if there is anything I should add beyond what was necessary for roaring. 
Closes: https://github.com/RoaringBitmap/roaring/issues/429
=> Start roaring64 validation

roaring.go, roaring_test.go
Same as https://github.com/RoaringBitmap/RoaringBitmap/pull/736 
This issue is only happening when target container is absent and a container exists with higher key.
In such case the previous value (if exist) must be in the container before the container returned by advanceUntil.
If a previous value doesn't exists (index is 0), then it simply returns -1 as it never enters the loop.
Test case is identical to the test added in java repository.
=> Fix previousValue not returning correct results in some cases

arraycontainer.go, bitmapcontainer.go, roaring_test.go
We should only use run containers if they are strictly smaller. Currently, when a container was just as concise using an array and a runcontainer, we would go back and forth with each optimization pass.
fixes https://github.com/RoaringBitmap/roaring/issues/440
=> fix: make RunOptimize idempotent

roaring64/roaring64.go, roaring64/roaring64cow_test.go, roaring64/serialization_test.go, roaring_test.go, roaringcow_test.go
Should fix an issue identified by @anacrolix 
See https://github.com/RoaringBitmap/roaring/pull/445
=> Fix returned value roaring64 from unsafe bytes

.github/workflows/bigendiantests.yml, .github/workflows/legacytests.yml, go.mod, go.sum, roaring64/bsi64.go, roaring64/bsi64_test.go
There is no fundamental reason why the BSI library cannot support values exceeding 64 bits.  Why is this necessary?   It would  now be possible to store values like UUID and 96 bit timestamps, as well as advanced string encodings in a BSI.
The BSI library has been modified to preserve the existing int64 interface and has been expanded to leverage the golang big.Int math library.   The original int64 methods now convert incoming values to *big.Int (and vice versa, etc).
Additional test coverage has been added and some of the original tests have been expanded.   
Performance does not seem to be substantially impacted.
=> BSI library expanded to include support for large arbitrary values via the big.Int library

BitSliceIndexing/bsi.go, BitSliceIndexing/bsi_test.go, roaring64/bsi64.go, roaring64/bsi64_test.go
i fixed fix use nil parameter, the MinMaxBig func will throw panic's problem (https://github.com/RoaringBitmap/roaring/issues/455)
=> fix use nil parameter, the MinMaxBig func will throw panic's problem

roaring64/bsi64.go, roaring64/bsi64_test.go
After calling NewDefaultBSI() and calling SetBigValue() with the value "0". The value is not inserted. This fails silently and only occurs then the BSI is empty. This is an edge case that was overlooked.
=> Fix issue 457.

runcontainer.go
There is no need to convert both run containers to bitmap containers first. There already is an efficient implementation of andNot in AndNotRunContainer16(), so use it.
=> runcontainer: make fewer memory allocations in iandNotRunContainer16().

arraycontainer.go
When AndAny is used with bitmaps that are using runcontainers that contain a range [x,65535], the resetTo arrayContainer panic with 'panic: runtime error: index out of range [length] with length [length]'.
This is because the loop in line 'arraycontainer.go#L969'  val is a uint16 and will overflow and will never be > r.last() as r.last() is MaxUint16.
=> Fixed a bug with AndAny, a case of uint16 overflow

roaring64/parallel64.go, roaring64/roaring64.go
We'd love to use the 64-bit variant to keep the implementation consistent across various use cases.
The merge performance of `roaring64.ParOr` suffers when all the bitmaps share the same upper 32 bits.
PS: I believe this behavior is correct. If it's not, let me know 😇
=> roaring64: Use roaring.ParOr when all keys on the roaringArray64 are same

BitSliceIndexing/bsi.go, BitSliceIndexing/bsi_test.go, roaring64/bsi64.go, roaring64/bsi64_test.go
We add `SetMany` as the bulk equivalent of `SetValue`.
Note: this PR adds new public methods.
Please let me know if we want to avoid doing that and also better name :)
=> Add SetMany and SetBigMany support
